[[ -f ~/.bashrc ]] && . ~/.bashrc

export BROWSER=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
export EDITOR=vim
export PLAN9=~/code/plan9port
export GOPATH=~/gocode
export GOROOT=~/go
export GOROOT_BOOTSTRAP=~/go1.8

export CDPATH=.:~:$GOROOT/src:$GOPATH/src/golang.org:$GOPATH/src/github.com:$GOPATH/src/github.com/davidrjenni:~/code

export PATH=~/Library/Android/sdk/platform-tools:$PATH
export PATH=$GOPATH/bin:$GOPATH/bin/darwin_amd64:$GOROOT/bin:~/code/go_appengine:$PATH
export PATH=$PATH:$PLAN9/bin:~/code/files/cmd:/usr/local/bin

if [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi

if ! pgrep -x "fontsrv" > /dev/null; then
	sh -c "nohup fontsrv &>/dev/null &"
fi
if ! pgrep -x "plumber" > /dev/null; then
	nohup plumber &>/dev/null
fi
if ! pgrep -x "godoc" > /dev/null; then
	sh -c "nohup sh -c 'godoc -http :6060 &>/dev/null' &>/dev/null &"
fi
