#!/bin/sh

source .bashrc
presmode on
xbindkeys &
plumber
fontsrv &
godoc -http :6060 &
feh --bg-fill --randomize ~/Pictures/Wallpapers/*
davmail &
while true; do
        xsetroot -name  " Bat. $(acpi -b | awk '{ print $4 " " $3 }' | tr -d ',') | Vol. $(amixer get Master | tail -1 | awk '{ if ($6 == "[off]") { print "m" $5 } else { print $5} }' | tr -d '[]') | $(date +"%a, %b %d %R") "
        sleep 10s
done &
exec dwm
